# CMake generated Testfile for 
# Source directory: /Users/praveengovindaraj/Neam_Home/repo/neam-nightly
# Build directory: /Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(vm_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/vm_test.exe")
set_tests_properties(vm_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;442;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(compiler_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/compiler_test.exe")
set_tests_properties(compiler_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;449;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(async_unit_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/async_unit_test.exe")
set_tests_properties(async_unit_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;455;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(runtime_executor_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/runtime_executor_test.exe")
set_tests_properties(runtime_executor_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;461;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(stdlib_list_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/stdlib_list_test.exe")
set_tests_properties(stdlib_list_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;467;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(stdlib_map_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/stdlib_map_test.exe")
set_tests_properties(stdlib_map_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;473;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(type_unification_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/type_unification_test.exe")
set_tests_properties(type_unification_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;495;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(test_framework_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/test_framework_test.exe")
set_tests_properties(test_framework_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;501;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(io_file_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/io_file_test.exe")
set_tests_properties(io_file_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;507;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(llm_adapter_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/llm_adapter_test.exe")
set_tests_properties(llm_adapter_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;522;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(http_client_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/http_client_test.exe")
set_tests_properties(http_client_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;528;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(package_manager_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/package_manager_test.exe")
set_tests_properties(package_manager_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;536;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(compile_run_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/compile_run_test.exe")
set_tests_properties(compile_run_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;542;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v068_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v068_test.exe")
set_tests_properties(v068_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;552;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v069_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v069_test.exe")
set_tests_properties(v069_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;562;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v070_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v070_test.exe")
set_tests_properties(v070_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;572;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v072_phase2_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v072_phase2_test.exe")
set_tests_properties(v072_phase2_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;582;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v072_manifest_agents_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v072_manifest_agents_test.exe")
set_tests_properties(v072_manifest_agents_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;588;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v090_data_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v090_data_agent_test.exe")
set_tests_properties(v090_data_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;598;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v091_etl_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v091_etl_agent_test.exe")
set_tests_properties(v091_etl_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;608;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v092_migration_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v092_migration_agent_test.exe")
set_tests_properties(v092_migration_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;618;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v093_dataops_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v093_dataops_agent_test.exe")
set_tests_properties(v093_dataops_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;628;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v094_governance_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v094_governance_agent_test.exe")
set_tests_properties(v094_governance_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;638;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v095_modeling_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v095_modeling_agent_test.exe")
set_tests_properties(v095_modeling_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;648;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v098_datascientist_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v098_datascientist_agent_test.exe")
set_tests_properties(v098_datascientist_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;658;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v0981_causal_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v0981_causal_agent_test.exe")
set_tests_properties(v0981_causal_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;664;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v0982_mlops_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v0982_mlops_agent_test.exe")
set_tests_properties(v0982_mlops_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;670;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v0983_databa_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v0983_databa_agent_test.exe")
set_tests_properties(v0983_databa_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;676;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v0984_datatest_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v0984_datatest_agent_test.exe")
set_tests_properties(v0984_datatest_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;682;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v099_dio_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v099_dio_agent_test.exe")
set_tests_properties(v099_dio_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;688;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v100_security_cloud_eval_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/v100_security_cloud_eval_test.exe")
set_tests_properties(v100_security_cloud_eval_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;695;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(neam_full_suite_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v10/neam_full_suite_test.exe")
set_tests_properties(neam_full_suite_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;705;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
subdirs("_deps/nlohmann_json-build")
subdirs("_deps/nlohmann_json_schema_validator-build")
subdirs("_deps/googletest-build")
subdirs("_deps/benchmark-build")
