//
// neam-forge — CLI binary for running forge agents from the command line
//
// Compiles and executes a .neam file, finds forge agents declared within,
// and invokes the forge loop via a generated bytecode wrapper.
//
// Usage: neam-forge --agent <file.neam> [--workspace <dir>] [--max-iterations <N>]
//                   [--max-cost <N>] [--name <agent_name>] [--verbose]
//

#include "neamc/pipeline.hpp"
#include "neamc/version.hpp"
#include "neamc/vm/forge_agent_type.hpp"
#include "neamc/vm/forge_loop.hpp"
#include "neamc/vm/value.hpp"
#include "neamc/vm/vm.hpp"

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

namespace
{

void print_usage()
{
  std::cout << "neam-forge " << NEAM_VERSION << " — Run forge agents from the command line\n\n"
            << "Usage: neam-forge --agent <file.neam> [options]\n\n"
            << "Options:\n"
            << "  --agent FILE          Path to .neam file containing forge agent (required)\n"
            << "  --name NAME           Name of forge agent to run (default: first found)\n"
            << "  --workspace DIR       Override workspace directory\n"
            << "  --max-iterations N    Override max iterations (default: agent config)\n"
            << "  --max-cost N          Override max cost (default: agent config)\n"
            << "  --verbose             Verbose output\n"
            << "  --help                Show this help message\n\n"
            << "Example:\n"
            << "  neam-forge --agent my_builder.neam --workspace ./out --max-iterations 10\n";
}

std::string to_std_string(const neamc::vm::ObjString* s)
{
  if (!s || !s->chars) return "";
  return std::string(s->chars, s->length);
}

}  // namespace

int main(int argc, char** argv)
{
  std::string agent_file;
  std::string agent_name;
  std::string workspace;
  int max_iterations = -1;
  double max_cost = -1.0;
  bool verbose = false;

  // Parse CLI args
  for (int i = 1; i < argc; ++i)
  {
    std::string arg = argv[i];

    if (arg == "--help" || arg == "-h")
    {
      print_usage();
      return 0;
    }
    else if (arg == "--agent" && i + 1 < argc)
    {
      agent_file = argv[++i];
    }
    else if (arg == "--name" && i + 1 < argc)
    {
      agent_name = argv[++i];
    }
    else if (arg == "--workspace" && i + 1 < argc)
    {
      workspace = argv[++i];
    }
    else if (arg == "--max-iterations" && i + 1 < argc)
    {
      max_iterations = std::stoi(argv[++i]);
    }
    else if (arg == "--max-cost" && i + 1 < argc)
    {
      max_cost = std::stod(argv[++i]);
    }
    else if (arg == "--verbose")
    {
      verbose = true;
    }
    else
    {
      std::cerr << "Unknown option: " << arg << "\n";
      print_usage();
      return 1;
    }
  }

  if (agent_file.empty())
  {
    std::cerr << "Error: --agent is required\n\n";
    print_usage();
    return 1;
  }

  // Read source file
  std::ifstream in(agent_file);
  if (!in)
  {
    std::cerr << "Error: cannot open file: " << agent_file << "\n";
    return 1;
  }
  std::string source((std::istreambuf_iterator<char>(in)),
                      std::istreambuf_iterator<char>());
  in.close();

  if (verbose)
  {
    std::cerr << "Compiling " << agent_file << "...\n";
  }

  try
  {
    // Compile the .neam file
    neamc::Pipeline pipeline;
    auto unit = pipeline.compile(source, {});

    // Execute the program to register agents
    neamc::vm::VirtualMachine vm;
    std::ostringstream out;
    std::istringstream in_stream;
    vm.set_io(&in_stream, &out);
    vm.run(unit.chunk);

    // Find the forge agent
    const auto& forge_agents = vm.forge_agents();
    if (forge_agents.empty())
    {
      std::cerr << "Error: no forge agents found in " << agent_file << "\n";
      return 1;
    }

    neamc::vm::ObjForgeAgent* forge = nullptr;
    if (!agent_name.empty())
    {
      auto it = forge_agents.find(agent_name);
      if (it == forge_agents.end())
      {
        std::cerr << "Error: forge agent '" << agent_name << "' not found. Available:";
        for (const auto& [name, _] : forge_agents)
        {
          std::cerr << " " << name;
        }
        std::cerr << "\n";
        return 1;
      }
      forge = it->second;
    }
    else
    {
      forge = forge_agents.begin()->second;
      agent_name = forge_agents.begin()->first;
    }

    if (verbose)
    {
      std::cerr << "Found forge agent: " << agent_name << "\n";
      std::cerr << "  Provider: " << to_std_string(forge->provider) << "\n";
      std::cerr << "  Model: " << to_std_string(forge->model) << "\n";
      std::cerr << "  Max iterations: " << forge->loop_config.max_iterations << "\n";
      std::cerr << "  Max cost: " << forge->loop_config.max_cost << "\n";
    }

    // Apply CLI overrides
    if (max_iterations > 0)
    {
      forge->loop_config.max_iterations = max_iterations;
    }
    if (max_cost > 0.0)
    {
      forge->loop_config.max_cost = max_cost;
    }
    if (!workspace.empty())
    {
      forge->workspace = workspace;
    }

    // Generate a wrapper program that calls forge_agent.run()
    // and execute it on the same VM that has the agents registered
    std::string wrapper_source =
        "{\n"
        "  let result = " + agent_name + ".run();\n"
        "  emit result;\n"
        "}\n";

    if (verbose)
    {
      std::cerr << "Running forge agent " << agent_name << "...\n";
    }

    neamc::Pipeline wrapper_pipeline;
    auto wrapper_unit = wrapper_pipeline.compile(wrapper_source, {});

    // Reset IO for the run
    std::ostringstream run_out;
    std::istringstream run_in;
    vm.set_io(&run_in, &run_out);
    vm.run(wrapper_unit.chunk);

    // Print emitted values
    for (const auto& emitted : vm.emitted())
    {
      std::cout << neamc::vm::value_to_string(emitted) << "\n";
    }

    // Also print any stdout output
    std::string stdout_output = run_out.str();
    if (!stdout_output.empty())
    {
      std::cout << stdout_output;
    }

    return 0;
  }
  catch (const std::exception& ex)
  {
    std::cerr << "Error: " << ex.what() << "\n";
    return 1;
  }
}
