#include "neamc/deploy.hpp"

#include <filesystem>
#include <fstream>
#include <iostream>

namespace neamc
{

namespace
{
// CloudFormation logical IDs must be alphanumeric.
// Convert "my-agent" → "MyAgent" (PascalCase)
std::string to_cfn_id(const std::string& name)
{
  std::string result;
  bool capitalize = true;
  for (char c : name)
  {
    if (c == '-' || c == '_' || c == '.')
    {
      capitalize = true;
      continue;
    }
    if (capitalize && c >= 'a' && c <= 'z')
    {
      result += static_cast<char>(c - 32);
      capitalize = false;
    }
    else
    {
      result += c;
      capitalize = false;
    }
  }
  return result.empty() ? "NeamAgent" : result;
}
}  // namespace

void generate_lambda_dockerfile(const DeployConfig& config, const std::string& app_name)
{
  namespace fs = std::filesystem;
  fs::create_directories("deploy/lambda");

  std::ofstream f("deploy/lambda/Dockerfile");
  f << "# Generated by neamc deploy --target lambda\n";
  f << "# v0.7.2: Uses neam-lambda custom runtime (no Web Adapter overhead)\n\n";

  // Build stage
  f << "# Stage 1: Build Neam toolchain\n";
  f << "FROM debian:bookworm AS builder\n\n";
  f << "RUN apt-get update && apt-get install -y --no-install-recommends \\\n";
  f << "        build-essential cmake ninja-build git ca-certificates \\\n";
  f << "        libcurl4-openssl-dev libssl-dev \\\n";
  f << "    && rm -rf /var/lib/apt/lists/*\n\n";
  f << "WORKDIR /neam-src\n";
  f << "COPY neam-sdk/ ./\n\n";
  f << "RUN cmake -B build -G Ninja \\\n";
  f << "        -DCMAKE_BUILD_TYPE=Release \\\n";
  f << "        -DCMAKE_INSTALL_PREFIX=/opt/neam \\\n";
  f << "    && cmake --build build --parallel \"$(nproc)\" \\\n";
  f << "    && cmake --install build\n\n";

  // Runtime stage — v0.7.2: uses neam-lambda custom runtime (no Web Adapter)
  f << "# Stage 2: Lambda runtime (neam-lambda custom runtime)\n";
  f << "FROM debian:bookworm-slim\n\n";
  f << "RUN apt-get update && apt-get install -y --no-install-recommends \\\n";
  f << "        ca-certificates libcurl4t64 libssl3 \\\n";
  f << "    && rm -rf /var/lib/apt/lists/*\n\n";

  f << "COPY --from=builder /opt/neam/bin/neam-lambda /usr/local/bin/neam-lambda\n";
  f << "COPY --from=builder /opt/neam/bin/neam-forge  /usr/local/bin/neam-forge\n";
  f << "COPY --from=builder /opt/neam/bin/neamc       /usr/local/bin/neamc\n";
  f << "COPY --from=builder /opt/neam/bin/neam        /usr/local/bin/neam\n";
  f << "COPY --from=builder /opt/neam/share/neam/stdlib/ /usr/local/share/neam/stdlib/\n\n";

  f << "WORKDIR /app\n";
  f << "COPY neam.toml .\n";
  f << "COPY src/ src/\n\n";

  f << "ENV NEAM_ENV=production\n";
  f << "ENV NEAM_LOG_LEVEL=info\n\n";

  f << "ENTRYPOINT [\"neam-lambda\"]\n";

  std::cout << "Generated deploy/lambda/Dockerfile\n";
  (void)app_name;
}

void generate_sam_template(const DeployConfig& config, const std::string& app_name)
{
  namespace fs = std::filesystem;
  fs::create_directories("deploy/lambda");

  // Also generate the Lambda Dockerfile
  generate_lambda_dockerfile(config, app_name);

  const int timeout = config.serverless.timeout;
  const int memory = config.serverless.memory;
  const int provisioned = config.serverless.provisioned_concurrency;
  const std::string cfn_id = to_cfn_id(app_name);

  std::ofstream f("deploy/lambda/template.yaml");
  f << "# Generated by neamc deploy --target lambda\n";
  f << "AWSTemplateFormatVersion: '2010-09-09'\n";
  f << "Transform: AWS::Serverless-2016-10-31\n";
  f << "Description: >\n";
  f << "  " << app_name << " - Neam agent deployed via AWS Lambda Web Adapter.\n";
  f << "  Wraps neam-api HTTP server as a Lambda function behind API Gateway v2.\n\n";

  // Parameters
  f << "Parameters:\n";
  f << "  Environment:\n";
  f << "    Type: String\n";
  f << "    Default: production\n";
  f << "    AllowedValues: [production, staging, development]\n";
  f << "  OpenAIApiKey:\n";
  f << "    Type: String\n";
  f << "    NoEcho: true\n";
  f << "    Description: OpenAI API key for LLM agents\n";
  f << "  NeamApiKey:\n";
  f << "    Type: String\n";
  f << "    NoEcho: true\n";
  f << "    Description: API authentication key\n";
  f << "  ImageUri:\n";
  f << "    Type: String\n";
  f << "    Description: ECR image URI for the Lambda container\n\n";

  // Globals
  f << "Globals:\n";
  f << "  Function:\n";
  f << "    Timeout: " << timeout << "\n";
  f << "    MemorySize: " << memory << "\n\n";

  // Resources
  f << "Resources:\n";
  f << "  " << cfn_id << "Function:\n";
  f << "    Type: AWS::Serverless::Function\n";
  f << "    Properties:\n";
  f << "      PackageType: Image\n";
  f << "      ImageUri: !Ref ImageUri\n";
  f << "      Architectures:\n";
  f << "        - x86_64\n";
  // v0.7.2: Auto-publish alias for provisioned concurrency
  if (provisioned > 0)
  {
    f << "      AutoPublishAlias: live\n";
    f << "      ProvisionedConcurrencyConfig:\n";
    f << "        ProvisionedConcurrentExecutions: " << provisioned << "\n";
  }
  f << "      Environment:\n";
  f << "        Variables:\n";
  f << "          NEAM_ENV: !Ref Environment\n";
  f << "          NEAM_LOG_LEVEL: info\n";
  f << "          OPENAI_API_KEY: !Ref OpenAIApiKey\n";
  f << "          NEAM_API_KEY: !Ref NeamApiKey\n";
  f << "      Events:\n";
  f << "        HealthCheck:\n";
  f << "          Type: HttpApi\n";
  f << "          Properties:\n";
  f << "            Path: /health\n";
  f << "            Method: GET\n";
  f << "        ReadyCheck:\n";
  f << "          Type: HttpApi\n";
  f << "          Properties:\n";
  f << "            Path: /ready\n";
  f << "            Method: GET\n";
  f << "        ApiHealth:\n";
  f << "          Type: HttpApi\n";
  f << "          Properties:\n";
  f << "            Path: /api/v1/health\n";
  f << "            Method: GET\n";
  f << "        ListAgents:\n";
  f << "          Type: HttpApi\n";
  f << "          Properties:\n";
  f << "            Path: /api/v1/agents\n";
  f << "            Method: GET\n";
  f << "        AgentAsk:\n";
  f << "          Type: HttpApi\n";
  f << "          Properties:\n";
  f << "            Path: /api/v1/agent/ask\n";
  f << "            Method: POST\n";
  f << "        ListClaw:\n";
  f << "          Type: HttpApi\n";
  f << "          Properties:\n";
  f << "            Path: /api/v1/claw\n";
  f << "            Method: GET\n";
  f << "        ClawMessage:\n";
  f << "          Type: HttpApi\n";
  f << "          Properties:\n";
  f << "            Path: /api/v1/claw/{agent}/sessions/{key}/message\n";
  f << "            Method: POST\n";
  f << "        ListForge:\n";
  f << "          Type: HttpApi\n";
  f << "          Properties:\n";
  f << "            Path: /api/v1/forge\n";
  f << "            Method: GET\n";
  f << "        ForgeStart:\n";
  f << "          Type: HttpApi\n";
  f << "          Properties:\n";
  f << "            Path: /api/v1/forge/{agent}/start\n";
  f << "            Method: POST\n";
  f << "        ForgeStop:\n";
  f << "          Type: HttpApi\n";
  f << "          Properties:\n";
  f << "            Path: /api/v1/forge/{agent}/stop\n";
  f << "            Method: POST\n";
  f << "        ForgeStatus:\n";
  f << "          Type: HttpApi\n";
  f << "          Properties:\n";
  f << "            Path: /api/v1/forge/{agent}/status\n";
  f << "            Method: GET\n";
  f << "        CatchAll:\n";
  f << "          Type: HttpApi\n";
  f << "          Properties:\n";
  f << "            Path: /{proxy+}\n";
  f << "            Method: ANY\n\n";

  // EFS for forge workspace persistence
  f << "  # EFS for forge agent workspace persistence\n";
  f << "  ForgeFileSystem:\n";
  f << "    Type: AWS::EFS::FileSystem\n";
  f << "    Properties:\n";
  f << "      PerformanceMode: generalPurpose\n";
  f << "      Encrypted: true\n";
  f << "      Tags:\n";
  f << "        - Key: Name\n";
  f << "          Value: !Sub ${AWS::StackName}-forge-workspace\n\n";
  f << "  ForgeAccessPoint:\n";
  f << "    Type: AWS::EFS::AccessPoint\n";
  f << "    Properties:\n";
  f << "      FileSystemId: !Ref ForgeFileSystem\n";
  f << "      PosixUser:\n";
  f << "        Uid: '1000'\n";
  f << "        Gid: '1000'\n";
  f << "      RootDirectory:\n";
  f << "        CreationInfo:\n";
  f << "          OwnerUid: '1000'\n";
  f << "          OwnerGid: '1000'\n";
  f << "          Permissions: '755'\n";
  f << "        Path: /workspace\n\n";

  f << "  LogGroup:\n";
  f << "    Type: AWS::Logs::LogGroup\n";
  f << "    Properties:\n";
  f << "      LogGroupName: !Sub /aws/lambda/${" << cfn_id << "Function}\n";
  f << "      RetentionInDays: 14\n\n";

  // Outputs
  f << "Outputs:\n";
  f << "  ApiUrl:\n";
  f << "    Description: API Gateway endpoint URL\n";
  f << "    Value: !Sub \"https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com\"\n";
  f << "  FunctionArn:\n";
  f << "    Description: Lambda function ARN\n";
  f << "    Value: !GetAtt " << cfn_id << "Function.Arn\n";
  f << "  FunctionName:\n";
  f << "    Description: Lambda function name\n";
  f << "    Value: !Ref " << cfn_id << "Function\n";

  std::cout << "Generated deploy/lambda/template.yaml\n";
  std::cout << "  PackageType: Image (Lambda Web Adapter)\n";
  std::cout << "  MemorySize: " << memory << " MB, Timeout: " << timeout << "s\n";
  std::cout << "  Endpoints: /health, /ready, /api/v1/*, /{proxy+}\n";
}
}  // namespace neamc
