// SPDX-License-Identifier: Apache-2.0
#include "neamc/deploy.hpp"

#include <filesystem>
#include <fstream>
#include <iostream>

namespace neamc
{
void generate_azure_container_apps(const ProjectManifest& manifest, const std::string& output_dir,
                                    bool dry_run)
{
  namespace fs = std::filesystem;
  const std::string dir = output_dir.empty() ? "deploy/azure" : output_dir + "/azure";
  fs::create_directories(dir);

  const auto& app_name = manifest.name;
  const auto& config = manifest.deploy;

  // Generate azure-container-app.yaml with KEDA scaling
  {
    std::ofstream file(dir + "/azure-container-app.yaml");
    file << "# Azure Container Apps manifest with KEDA scaling\n";
    file << "# Generated by Neam v0.6.0\n";
    file << "apiVersion: apps/v1\n";
    file << "kind: ContainerApp\n";
    file << "metadata:\n";
    file << "  name: " << app_name << "\n";
    file << "  resourceGroup: " << app_name << "-rg\n";
    file << "  location: eastus\n";
    file << "properties:\n";
    file << "  managedEnvironmentId: /subscriptions/<SUBSCRIPTION_ID>/resourceGroups/"
         << app_name << "-rg/providers/Microsoft.App/managedEnvironments/" << app_name
         << "-env\n";
    file << "  configuration:\n";
    file << "    ingress:\n";
    file << "      external: true\n";
    file << "      targetPort: " << config.kubernetes.port << "\n";
    file << "      transport: auto\n";
    file << "    registries:\n";
    file << "    - server: " << config.docker.registry << "\n";
    file << "      identity: system\n";
    file << "    secrets:\n";
    file << "    - name: neam-api-key\n";
    file << "      keyVaultUrl: https://" << app_name << "-kv.vault.azure.net/secrets/neam-api-key\n";
    file << "      identity: system\n";
    file << "  template:\n";
    file << "    containers:\n";
    file << "    - name: " << app_name << "\n";
    file << "      image: " << config.docker.image << "\n";
    file << "      resources:\n";
    file << "        cpu: 0.5\n";
    file << "        memory: 1Gi\n";
    file << "      env:\n";
    file << "      - name: NEAM_ENV\n";
    file << "        value: production\n";
    file << "      - name: NEAM_LOG_LEVEL\n";
    file << "        value: info\n";
    file << "      - name: NEAM_API_KEY\n";
    file << "        secretRef: neam-api-key\n";
    file << "      probes:\n";
    file << "      - type: liveness\n";
    file << "        httpGet:\n";
    file << "          path: /health\n";
    file << "          port: " << config.kubernetes.port << "\n";
    file << "        initialDelaySeconds: 10\n";
    file << "        periodSeconds: 10\n";
    file << "      - type: readiness\n";
    file << "        httpGet:\n";
    file << "          path: /ready\n";
    file << "          port: " << config.kubernetes.port << "\n";
    file << "        initialDelaySeconds: 5\n";
    file << "        periodSeconds: 5\n";
    file << "    scale:\n";
    file << "      minReplicas: 1\n";
    file << "      maxReplicas: 10\n";
    file << "      rules:\n";
    file << "      - name: http-scaling\n";
    file << "        http:\n";
    file << "          metadata:\n";
    file << "            concurrentRequests: \"50\"\n";
    file << "      - name: cpu-scaling\n";
    file << "        custom:\n";
    file << "          type: cpu\n";
    file << "          metadata:\n";
    file << "            type: Utilization\n";
    file << "            value: \"70\"\n";
  }

  // Generate azure-deploy.sh script
  {
    std::ofstream file(dir + "/azure-deploy.sh");
    file << "#!/usr/bin/env bash\n";
    file << "# Azure Container Apps deployment script\n";
    file << "# Generated by Neam v0.6.0\n";
    file << "set -euo pipefail\n\n";
    file << "APP_NAME=\"" << app_name << "\"\n";
    file << "RESOURCE_GROUP=\"${APP_NAME}-rg\"\n";
    file << "LOCATION=\"eastus\"\n";
    file << "ENVIRONMENT=\"${APP_NAME}-env\"\n";
    file << "REGISTRY=\"" << config.docker.registry << "\"\n";
    file << "IMAGE=\"" << config.docker.image << "\"\n\n";
    file << "echo \"==> Creating resource group...\"\n";
    file << "az group create --name \"$RESOURCE_GROUP\" --location \"$LOCATION\"\n\n";
    file << "echo \"==> Creating Container Apps environment...\"\n";
    file << "az containerapp env create \\\n";
    file << "  --name \"$ENVIRONMENT\" \\\n";
    file << "  --resource-group \"$RESOURCE_GROUP\" \\\n";
    file << "  --location \"$LOCATION\"\n\n";
    file << "echo \"==> Building and pushing container image...\"\n";
    file << "az acr build --registry \"$REGISTRY\" --image \"$IMAGE\" .\n\n";
    file << "echo \"==> Deploying Container App...\"\n";
    file << "az containerapp create \\\n";
    file << "  --name \"$APP_NAME\" \\\n";
    file << "  --resource-group \"$RESOURCE_GROUP\" \\\n";
    file << "  --environment \"$ENVIRONMENT\" \\\n";
    file << "  --image \"$IMAGE\" \\\n";
    file << "  --target-port " << config.kubernetes.port << " \\\n";
    file << "  --ingress external \\\n";
    file << "  --min-replicas 1 \\\n";
    file << "  --max-replicas 10 \\\n";
    file << "  --cpu 0.5 \\\n";
    file << "  --memory 1Gi \\\n";
    file << "  --env-vars NEAM_ENV=production NEAM_LOG_LEVEL=info\n\n";
    file << "echo \"==> Deployment complete.\"\n";
    file << "az containerapp show --name \"$APP_NAME\" --resource-group \"$RESOURCE_GROUP\" "
         << "--query 'properties.configuration.ingress.fqdn' -o tsv\n";
  }

  if (dry_run)
  {
    std::cout << "[dry-run] Would generate Azure Container Apps manifests in " << dir << "/\n";
  }
  else
  {
    std::cout << "Generated Azure Container Apps manifests in " << dir << "/\n";
  }
}
}  // namespace neamc
