// SPDX-License-Identifier: Apache-2.0
#include "neamc/deploy.hpp"

#include <filesystem>
#include <fstream>
#include <iostream>

namespace neamc
{
void generate_azure_aks(const ProjectManifest& manifest, const std::string& output_dir,
                         bool dry_run)
{
  namespace fs = std::filesystem;
  const std::string dir = output_dir.empty() ? "deploy/aks" : output_dir + "/aks";
  fs::create_directories(dir);

  const auto& app_name = manifest.name;
  const auto& config = manifest.deploy;
  const auto& k8s = config.kubernetes;

  // Generate AKS deployment with Workload Identity annotations
  {
    std::ofstream file(dir + "/deployment.yaml");
    file << "# AKS Deployment with Workload Identity\n";
    file << "# Generated by Neam v0.6.0\n";
    file << "apiVersion: apps/v1\n";
    file << "kind: Deployment\n";
    file << "metadata:\n";
    file << "  name: " << app_name << "\n";
    file << "  namespace: " << k8s.namespace_ << "\n";
    file << "  labels:\n";
    file << "    app: " << app_name << "\n";
    file << "    azure.workload.identity/use: \"true\"\n";
    file << "spec:\n";
    file << "  replicas: " << k8s.replicas << "\n";
    file << "  selector:\n";
    file << "    matchLabels:\n";
    file << "      app: " << app_name << "\n";
    file << "  template:\n";
    file << "    metadata:\n";
    file << "      labels:\n";
    file << "        app: " << app_name << "\n";
    file << "        azure.workload.identity/use: \"true\"\n";
    file << "    spec:\n";
    file << "      serviceAccountName: " << app_name << "-sa\n";
    file << "      containers:\n";
    file << "      - name: " << app_name << "\n";
    file << "        image: " << config.docker.image << "\n";
    file << "        ports:\n";
    file << "        - containerPort: " << k8s.port << "\n";
    file << "        resources:\n";
    file << "          requests:\n";
    file << "            cpu: " << k8s.cpu << "\n";
    file << "            memory: " << k8s.memory << "\n";
    file << "          limits:\n";
    file << "            cpu: " << k8s.cpu << "\n";
    file << "            memory: " << k8s.memory << "\n";
    file << "        env:\n";
    file << "        - name: NEAM_ENV\n";
    file << "          value: production\n";
    file << "        - name: AZURE_CLIENT_ID\n";
    file << "          valueFrom:\n";
    file << "            secretKeyRef:\n";
    file << "              name: " << app_name << "-identity\n";
    file << "              key: clientId\n";
    file << "        envFrom:\n";
    file << "        - secretRef:\n";
    file << "            name: " << app_name << "-secrets\n";
    file << "        livenessProbe:\n";
    file << "          httpGet:\n";
    file << "            path: /health\n";
    file << "            port: " << k8s.port << "\n";
    file << "          initialDelaySeconds: 10\n";
    file << "          periodSeconds: 10\n";
    file << "        readinessProbe:\n";
    file << "          httpGet:\n";
    file << "            path: /ready\n";
    file << "            port: " << k8s.port << "\n";
    file << "          initialDelaySeconds: 5\n";
    file << "          periodSeconds: 5\n";
  }

  // Generate ServiceAccount with Workload Identity annotation
  {
    std::ofstream file(dir + "/service-account.yaml");
    file << "# AKS Service Account with Workload Identity\n";
    file << "# Generated by Neam v0.6.0\n";
    file << "apiVersion: v1\n";
    file << "kind: ServiceAccount\n";
    file << "metadata:\n";
    file << "  name: " << app_name << "-sa\n";
    file << "  namespace: " << k8s.namespace_ << "\n";
    file << "  annotations:\n";
    file << "    azure.workload.identity/client-id: <AZURE_CLIENT_ID>\n";
    file << "  labels:\n";
    file << "    azure.workload.identity/use: \"true\"\n";
  }

  // Generate Service
  {
    std::ofstream file(dir + "/service.yaml");
    file << "# AKS Service\n";
    file << "# Generated by Neam v0.6.0\n";
    file << "apiVersion: v1\n";
    file << "kind: Service\n";
    file << "metadata:\n";
    file << "  name: " << app_name << "\n";
    file << "  namespace: " << k8s.namespace_ << "\n";
    file << "spec:\n";
    file << "  selector:\n";
    file << "    app: " << app_name << "\n";
    file << "  ports:\n";
    file << "  - port: 80\n";
    file << "    targetPort: " << k8s.port << "\n";
    file << "  type: ClusterIP\n";
  }

  if (dry_run)
  {
    std::cout << "[dry-run] Would generate AKS manifests in " << dir << "/\n";
  }
  else
  {
    std::cout << "Generated AKS manifests in " << dir << "/\n";
  }
}
}  // namespace neamc
