#include "neamc/deploy.hpp"

#include <filesystem>
#include <fstream>
#include <iostream>

namespace neamc
{

void generate_deploy_scripts(const DeployConfig& config, const std::string& app_name,
                             const std::string& image)
{
  namespace fs = std::filesystem;
  fs::create_directories("deploy/scripts");

  const std::string ns = config.kubernetes.namespace_;
  const std::string registry = config.docker.registry;

  // --- ecr-push.sh ---
  {
    std::ofstream f("deploy/scripts/ecr-push.sh");
    f << "#!/usr/bin/env bash\n";
    f << "# Generated by neamc deploy\n";
    f << "# Push " << app_name << " Docker image to AWS ECR\n";
    f << "set -euo pipefail\n\n";

    f << "ACCOUNT_ID=\"${AWS_ACCOUNT_ID:?Set AWS_ACCOUNT_ID}\"\n";
    f << "REGION=\"${AWS_REGION:-us-east-1}\"\n";
    f << "REPO=\"" << app_name << "\"\n";
    f << "TAG=\"${1:-latest}\"\n";
    f << "REGISTRY=\"${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com\"\n";
    f << "IMAGE=\"${REGISTRY}/${REPO}\"\n\n";

    f << "# Create ECR repo if needed\n";
    f << "aws ecr describe-repositories --repository-names \"$REPO\" --region \"$REGION\" 2>/dev/null || \\\n";
    f << "  aws ecr create-repository --repository-name \"$REPO\" --region \"$REGION\" \\\n";
    f << "    --image-scanning-configuration scanOnPush=true\n\n";

    f << "# Login\n";
    f << "aws ecr get-login-password --region \"$REGION\" | \\\n";
    f << "  docker login --username AWS --password-stdin \"$REGISTRY\"\n\n";

    f << "# Build and push\n";
    f << "docker build --platform linux/amd64 -f deploy/docker/Dockerfile \\\n";
    f << "  -t \"${IMAGE}:${TAG}\" -t \"${IMAGE}:latest\" .\n";
    f << "docker push \"${IMAGE}:${TAG}\"\n";
    f << "docker push \"${IMAGE}:latest\"\n\n";
    f << "echo \"Pushed: ${IMAGE}:${TAG}\"\n";

    fs::permissions("deploy/scripts/ecr-push.sh",
                    fs::perms::owner_exec | fs::perms::group_exec | fs::perms::others_exec,
                    fs::perm_options::add);
  }

  // --- eks-deploy.sh ---
  {
    std::ofstream f("deploy/scripts/eks-deploy.sh");
    f << "#!/usr/bin/env bash\n";
    f << "# Generated by neamc deploy\n";
    f << "# Deploy " << app_name << " to AWS EKS\n";
    f << "set -euo pipefail\n\n";

    f << "ACCOUNT_ID=\"${AWS_ACCOUNT_ID:?Set AWS_ACCOUNT_ID}\"\n";
    f << "REGION=\"${AWS_REGION:-us-east-1}\"\n";
    f << "CLUSTER=\"${EKS_CLUSTER_NAME:?Set EKS_CLUSTER_NAME}\"\n";
    f << "TAG=\"${1:-latest}\"\n";
    f << "IMAGE=\"${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/" << app_name << ":${TAG}\"\n\n";

    f << "# Update kubeconfig\n";
    f << "aws eks update-kubeconfig --name \"$CLUSTER\" --region \"$REGION\"\n\n";

    f << "# Apply manifests\n";
    f << "kubectl apply -f deploy/kubernetes/namespace.yaml\n";
    f << "kubectl apply -f deploy/kubernetes/configmap.yaml\n";
    f << "kubectl apply -f deploy/kubernetes/secrets.yaml\n\n";

    f << "# Substitute image and apply deployment\n";
    f << "sed \"s|" << image << "|${IMAGE}|g\" deploy/kubernetes/deployment.yaml | kubectl apply -f -\n\n";

    f << "kubectl apply -f deploy/kubernetes/service.yaml\n";
    f << "kubectl apply -f deploy/kubernetes/ingress.yaml\n";
    f << "kubectl apply -f deploy/kubernetes/hpa.yaml\n\n";

    f << "# Wait for rollout\n";
    f << "kubectl rollout status deployment/" << app_name << " -n " << ns << " --timeout=300s\n";
    f << "kubectl get pods -n " << ns << " -l app.kubernetes.io/name=" << app_name << "\n";

    fs::permissions("deploy/scripts/eks-deploy.sh",
                    fs::perms::owner_exec | fs::perms::group_exec | fs::perms::others_exec,
                    fs::perm_options::add);
  }

  // --- lambda-deploy.sh ---
  {
    std::ofstream f("deploy/scripts/lambda-deploy.sh");
    f << "#!/usr/bin/env bash\n";
    f << "# Generated by neamc deploy\n";
    f << "# Deploy " << app_name << " to AWS Lambda\n";
    f << "set -euo pipefail\n\n";

    f << "ACCOUNT_ID=\"${AWS_ACCOUNT_ID:?Set AWS_ACCOUNT_ID}\"\n";
    f << "REGION=\"${AWS_REGION:-us-east-1}\"\n";
    f << "REPO=\"" << app_name << "-lambda\"\n";
    f << "TAG=\"${1:-latest}\"\n";
    f << "REGISTRY=\"${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com\"\n";
    f << "IMAGE=\"${REGISTRY}/${REPO}\"\n";
    f << "STACK_NAME=\"" << app_name << "-lambda\"\n\n";

    f << "# Create ECR repo if needed\n";
    f << "aws ecr describe-repositories --repository-names \"$REPO\" --region \"$REGION\" 2>/dev/null || \\\n";
    f << "  aws ecr create-repository --repository-name \"$REPO\" --region \"$REGION\" \\\n";
    f << "    --image-scanning-configuration scanOnPush=true\n\n";

    f << "# Login, build, push\n";
    f << "aws ecr get-login-password --region \"$REGION\" | \\\n";
    f << "  docker login --username AWS --password-stdin \"$REGISTRY\"\n";
    f << "docker build --platform linux/amd64 -f deploy/lambda/Dockerfile \\\n";
    f << "  -t \"${IMAGE}:${TAG}\" .\n";
    f << "docker push \"${IMAGE}:${TAG}\"\n\n";

    f << "# SAM deploy\n";
    f << "sam deploy \\\n";
    f << "  --template-file deploy/lambda/template.yaml \\\n";
    f << "  --stack-name \"$STACK_NAME\" \\\n";
    f << "  --region \"$REGION\" \\\n";
    f << "  --capabilities CAPABILITY_IAM \\\n";
    f << "  --no-fail-on-empty-changeset \\\n";
    f << "  --parameter-overrides \\\n";
    f << "    \"OpenAIApiKey=${OPENAI_API_KEY:-}\" \\\n";
    f << "    \"NeamApiKey=${NEAM_API_KEY:-}\" \\\n";
    f << "    \"ImageUri=${IMAGE}:${TAG}\"\n\n";

    f << "# Print API URL\n";
    f << "aws cloudformation describe-stacks --stack-name \"$STACK_NAME\" --region \"$REGION\" \\\n";
    f << "  --query 'Stacks[0].Outputs[*].[OutputKey,OutputValue]' --output table\n";

    fs::permissions("deploy/scripts/lambda-deploy.sh",
                    fs::perms::owner_exec | fs::perms::group_exec | fs::perms::others_exec,
                    fs::perm_options::add);
  }

  std::cout << "Generated deploy scripts in deploy/scripts/\n";
  std::cout << "  ecr-push.sh       - Build & push to ECR\n";
  std::cout << "  eks-deploy.sh     - Deploy to EKS cluster\n";
  std::cout << "  lambda-deploy.sh  - Deploy to AWS Lambda\n";
}
}  // namespace neamc
