#include "neamc/deploy.hpp"

#include <filesystem>
#include <fstream>
#include <iostream>

namespace neamc
{
void generate_dockerfile(const DeployConfig& config, const std::string& app_name)
{
  namespace fs = std::filesystem;
  fs::create_directories("deploy/docker");

  const int port = config.kubernetes.port;
  const std::string registry = config.docker.registry;
  const std::string image = config.docker.image.empty() ? app_name : config.docker.image;

  // --- Dockerfile ---
  std::ofstream file("deploy/docker/Dockerfile");
  file << "# Generated by neamc deploy --target docker\n";
  file << "# Neam application: " << app_name << "\n";
  file << "#\n";
  file << "# Build context must be the project root (where neam.toml lives).\n";
  file << "#   docker build -f deploy/docker/Dockerfile -t " << app_name << " .\n";
  file << "#\n";
  file << "# The Neam SDK source must be available at ./neam-sdk/ in the build context.\n";
  file << "# Get it via:  git clone https://github.com/neam-lang/neam.git neam-sdk\n";
  file << "#   or:        neam-pkg vendor-sdk\n\n";

  // Stage 1: Build Neam toolchain from SDK source
  file << "# ── Stage 1: Build Neam toolchain ──────────────────────────────\n";
  file << "FROM debian:bookworm AS toolchain\n\n";
  file << "RUN apt-get update && apt-get install -y --no-install-recommends \\\n";
  file << "        build-essential cmake ninja-build git ca-certificates \\\n";
  file << "        libcurl4-openssl-dev libssl-dev \\\n";
  file << "    && rm -rf /var/lib/apt/lists/*\n\n";
  file << "WORKDIR /neam-sdk\n";
  file << "COPY neam-sdk/ .\n\n";
  file << "RUN cmake -B build -G Ninja \\\n";
  file << "        -DCMAKE_BUILD_TYPE=Release \\\n";
  file << "        -DCMAKE_INSTALL_PREFIX=/opt/neam \\\n";
  file << "    && cmake --build build --parallel \"$(nproc)\" \\\n";
  file << "    && cmake --install build\n\n";

  // Stage 2: Production image with toolchain + user app
  file << "# ── Stage 2: Application ───────────────────────────────────────\n";
  file << "FROM debian:bookworm-slim\n\n";
  file << "RUN apt-get update && apt-get install -y --no-install-recommends \\\n";
  file << "        ca-certificates libcurl4t64 libssl3 curl \\\n";
  file << "    && rm -rf /var/lib/apt/lists/*\n\n";

  // Neam toolchain
  file << "# Neam toolchain\n";
  file << "COPY --from=toolchain /opt/neam/bin/neam-api   /usr/local/bin/neam-api\n";
  file << "COPY --from=toolchain /opt/neam/bin/neamc      /usr/local/bin/neamc\n";
  file << "COPY --from=toolchain /opt/neam/bin/neam       /usr/local/bin/neam\n";
  file << "COPY --from=toolchain /opt/neam/bin/neam-pkg   /usr/local/bin/neam-pkg\n";
  file << "COPY --from=toolchain /opt/neam/share/neam/stdlib/ /usr/local/share/neam/stdlib/\n\n";

  // Non-root user
  file << "# Non-root user\n";
  file << "RUN groupadd -r neam && useradd -r -g neam -d /app -s /sbin/nologin neam \\\n";
  file << "    && mkdir -p /app && chown neam:neam /app\n\n";

  // User application (project files)
  file << "# Application source\n";
  file << "WORKDIR /app\n";
  file << "COPY neam.toml .\n";
  file << "COPY src/ src/\n";
  file << "RUN chown -R neam:neam /app\n";
  file << "USER neam\n\n";

  file << "ENV NEAM_ENV=production\n";
  file << "ENV NEAM_LOG_LEVEL=info\n\n";
  file << "EXPOSE " << port << "\n\n";

  file << "HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\\n";
  file << "    CMD curl -sf http://localhost:" << port << "/health || exit 1\n\n";

  file << "ENTRYPOINT [\"neam-api\"]\n";
  file << "CMD [\"--port\", \"" << port << "\", \"--workers\", \"4\"]\n";

  // --- .dockerignore ---
  {
    std::ofstream di(".dockerignore");
    di << "# Generated by neamc deploy\n";
    di << "target/\n";
    di << "deploy/\n";
    di << "tests/\n";
    di << ".git/\n";
    di << ".gitignore\n";
    di << "*.md\n";
    di << "neam.lock\n";
    di << ".gitlab-ci.yml\n";
    di << ".github/\n";
  }

  // --- docker-compose.yml ---
  std::ofstream compose("deploy/docker/docker-compose.yml");
  compose << "# Generated by neamc deploy --target docker\n";
  compose << "#   docker compose -f deploy/docker/docker-compose.yml up\n";
  compose << "services:\n";
  compose << "  " << app_name << ":\n";
  compose << "    build:\n";
  compose << "      context: ../..\n";
  compose << "      dockerfile: deploy/docker/Dockerfile\n";
  compose << "    ports:\n";
  compose << "      - \"" << port << ":" << port << "\"\n";
  compose << "    environment:\n";
  compose << "      - NEAM_ENV=development\n";
  compose << "      - NEAM_LOG_LEVEL=debug\n";
  compose << "      - OPENAI_API_KEY=${OPENAI_API_KEY:-}\n";
  compose << "      - NEAM_API_KEY=${NEAM_API_KEY:-}\n";
  compose << "    healthcheck:\n";
  compose << "      test: [\"CMD\", \"curl\", \"-sf\", \"http://localhost:" << port << "/health\"]\n";
  compose << "      interval: 15s\n";
  compose << "      timeout: 5s\n";
  compose << "      retries: 3\n";
  compose << "      start_period: 10s\n";
  compose << "    restart: unless-stopped\n";

  std::cout << "Generated deploy/docker/Dockerfile\n";
  std::cout << "Generated deploy/docker/docker-compose.yml\n";
  std::cout << "Generated .dockerignore\n";
}
}  // namespace neamc
