// SPDX-License-Identifier: Apache-2.0
#include "neamc/deploy.hpp"

#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

namespace neamc
{

/// Generate a deploy/docker/push.sh script that builds, tags, and pushes
/// the Neam agent Docker image to a container registry, and optionally
/// applies Kubernetes manifests.
void generate_docker_push(const DeployConfig& config)
{
  namespace fs = std::filesystem;
  fs::create_directories("deploy/docker");

  const std::string registry =
      config.docker.registry.empty() ? "ghcr.io" : config.docker.registry;
  const std::string image_name =
      config.docker.image.empty() ? "neam-agent" : config.docker.image;
  const std::string tag =
      config.docker.tag_format.empty() ? "latest" : config.docker.tag_format;
  const std::string namespace_name = config.kubernetes.namespace_;
  const std::string gitops_overlay = "production";

  std::ostringstream script;

  script << "#!/usr/bin/env bash\n";
  script << "# =============================================================================\n";
  script << "# Neam Docker Build, Tag & Push Script\n";
  script << "# Generated by neamc deploy --docker-push\n";
  script << "# =============================================================================\n";
  script << "set -euo pipefail\n\n";

  script << "# Configuration (override via environment variables)\n";
  script << "REGISTRY=\"${NEAM_REGISTRY:-" << registry << "}\"\n";
  script << "IMAGE_NAME=\"${NEAM_IMAGE:-" << image_name << "}\"\n";
  script << "TAG=\"${NEAM_TAG:-" << tag << "}\"\n";
  script << "NAMESPACE=\"${NEAM_K8S_NAMESPACE:-" << namespace_name << "}\"\n";
  script << "GITOPS_OVERLAY=\"${NEAM_GITOPS_OVERLAY:-" << gitops_overlay << "}\"\n";
  script << "DOCKERFILE=\"${NEAM_DOCKERFILE:-Dockerfile}\"\n";
  script << "BUILD_CONTEXT=\"${NEAM_BUILD_CONTEXT:-.}\"\n";
  script << "APPLY_K8S=\"${NEAM_APPLY_K8S:-false}\"\n";
  script << "FULL_IMAGE=\"${REGISTRY}/${IMAGE_NAME}\"\n\n";

  script << "info()  { echo -e \"\\033[1;34m[INFO]\\033[0m  $*\"; }\n";
  script << "ok()    { echo -e \"\\033[1;32m[OK]\\033[0m    $*\"; }\n";
  script << "err()   { echo -e \"\\033[1;31m[ERROR]\\033[0m $*\" >&2; }\n\n";

  script << "info \"Pre-flight checks...\"\n";
  script << "if ! command -v docker &>/dev/null; then\n";
  script << "  err \"docker is not installed or not in PATH\"\n";
  script << "  exit 1\n";
  script << "fi\n\n";

  script << "if [ \"${APPLY_K8S}\" = \"true\" ]; then\n";
  script << "  if ! command -v kubectl &>/dev/null; then\n";
  script << "    err \"kubectl is not installed but APPLY_K8S=true\"\n";
  script << "    exit 1\n";
  script << "  fi\n";
  script << "fi\n\n";

  script << "info \"Building image ${FULL_IMAGE}:${TAG} ...\"\n";
  script << "docker build \\\n";
  script << "  -f \"${DOCKERFILE}\" \\\n";
  script << "  -t \"${FULL_IMAGE}:${TAG}\" \\\n";
  script << "  -t \"${FULL_IMAGE}:latest\" \\\n";
  script << "  --label \"org.opencontainers.image.version=${TAG}\" \\\n";
  script << "  --label \"org.opencontainers.image.source=https://github.com/praveengovindaraj/Neam\" \\\n";
  script << "  --label \"org.opencontainers.image.created=$(date -u +%Y-%m-%dT%H:%M:%SZ)\" \\\n";
  script << "  \"${BUILD_CONTEXT}\"\n";
  script << "ok \"Image built successfully.\"\n\n";

  script << "info \"Pushing ${FULL_IMAGE}:${TAG} ...\"\n";
  script << "docker push \"${FULL_IMAGE}:${TAG}\"\n";
  script << "docker push \"${FULL_IMAGE}:latest\"\n";
  script << "ok \"Image pushed to ${REGISTRY}.\"\n\n";

  script << "DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' \"${FULL_IMAGE}:${TAG}\" 2>/dev/null || true)\n";
  script << "if [ -n \"${DIGEST}\" ]; then\n";
  script << "  echo \"${DIGEST}\" > deploy/docker/digest.txt\n";
  script << "  info \"Digest written to deploy/docker/digest.txt\"\n";
  script << "fi\n\n";

  script << "if [ \"${APPLY_K8S}\" = \"true\" ]; then\n";
  script << "  info \"Applying Kubernetes manifests (overlay: ${GITOPS_OVERLAY}) ...\"\n";
  script << "  GITOPS_DIR=\"gitops/overlays/${GITOPS_OVERLAY}\"\n";
  script << "  if [ ! -d \"${GITOPS_DIR}\" ]; then\n";
  script << "    err \"GitOps overlay directory not found: ${GITOPS_DIR}\"\n";
  script << "    exit 1\n";
  script << "  fi\n";
  script << "  if command -v kustomize &>/dev/null; then\n";
  script << "    (cd \"${GITOPS_DIR}\" && kustomize edit set image \"neam-agent=${FULL_IMAGE}:${TAG}\")\n";
  script << "  fi\n";
  script << "  kubectl apply -k \"${GITOPS_DIR}\"\n";
  script << "  info \"Waiting for rollout to complete...\"\n";
  script << "  kubectl rollout status deployment/neam-agent -n \"${NAMESPACE}\" --timeout=300s\n";
  script << "  ok \"Kubernetes deployment updated successfully.\"\n";
  script << "else\n";
  script << "  info \"Skipping Kubernetes apply (set NEAM_APPLY_K8S=true to enable).\"\n";
  script << "fi\n\n";

  script << "echo \"\"\n";
  script << "echo \"=========================================\"\n";
  script << "echo \" Deployment Summary\"\n";
  script << "echo \"=========================================\"\n";
  script << "echo \" Registry : ${REGISTRY}\"\n";
  script << "echo \" Image    : ${IMAGE_NAME}\"\n";
  script << "echo \" Tag      : ${TAG}\"\n";
  script << "echo \" Full     : ${FULL_IMAGE}:${TAG}\"\n";
  script << "ok \"Done.\"\n";

  const std::string script_path = "deploy/docker/push.sh";
  std::ofstream file(script_path);
  if (!file.is_open())
  {
    std::cerr << "Error: could not open " << script_path << " for writing\n";
    return;
  }
  file << script.str();
  file.close();

  fs::permissions(script_path,
                  fs::perms::owner_exec | fs::perms::group_exec | fs::perms::others_exec,
                  fs::perm_options::add);

  std::cout << "Generated " << script_path << "\n";
  std::cout << "  Registry : " << registry << "\n";
  std::cout << "  Image    : " << image_name << "\n";
  std::cout << "  Tag      : " << tag << "\n";
  std::cout << "\nUsage:\n";
  std::cout << "  bash deploy/docker/push.sh\n";
  std::cout << "  NEAM_APPLY_K8S=true bash deploy/docker/push.sh\n";
}

}  // namespace neamc
