#include "neamc/deploy.hpp"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>

namespace neamc
{

namespace
{
// K8s labels must match [a-z0-9]([-a-z0-9]*[a-z0-9])?
// Replace underscores and other invalid chars with hyphens
std::string sanitize_k8s_name(const std::string& name)
{
  std::string result;
  result.reserve(name.size());
  for (char c : name)
  {
    if ((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-')
    {
      result += c;
    }
    else if (c >= 'A' && c <= 'Z')
    {
      result += static_cast<char>(c + 32);  // tolower
    }
    else
    {
      result += '-';
    }
  }
  // Strip leading/trailing hyphens
  while (!result.empty() && result.front() == '-')
    result.erase(result.begin());
  while (!result.empty() && result.back() == '-')
    result.pop_back();
  return result.empty() ? "neam-app" : result;
}
}  // namespace

void generate_k8s_manifests(const DeployConfig::Kubernetes& config, const std::string& app_name,
                            const std::string& image)
{
  namespace fs = std::filesystem;
  fs::create_directories("deploy/kubernetes");

  const std::string name = sanitize_k8s_name(app_name);

  // --- namespace.yaml ---
  {
    std::ofstream f("deploy/kubernetes/namespace.yaml");
    f << "# Generated by neamc deploy --target kubernetes\n";
    f << "apiVersion: v1\n";
    f << "kind: Namespace\n";
    f << "metadata:\n";
    f << "  name: " << config.namespace_ << "\n";
    f << "  labels:\n";
    f << "    app.kubernetes.io/name: " << name << "\n";
    f << "    app.kubernetes.io/part-of: neam-platform\n";
  }

  // --- configmap.yaml ---
  {
    std::ofstream f("deploy/kubernetes/configmap.yaml");
    f << "# Generated by neamc deploy --target kubernetes\n";
    f << "apiVersion: v1\n";
    f << "kind: ConfigMap\n";
    f << "metadata:\n";
    f << "  name: " << name << "-config\n";
    f << "  namespace: " << config.namespace_ << "\n";
    f << "  labels:\n";
    f << "    app.kubernetes.io/name: " << name << "\n";
    f << "data:\n";
    f << "  NEAM_ENV: \"production\"\n";
    f << "  NEAM_LOG_LEVEL: \"info\"\n";
  }

  // --- secrets.yaml ---
  {
    std::ofstream f("deploy/kubernetes/secrets.yaml");
    f << "# Generated by neamc deploy --target kubernetes\n";
    f << "# Replace empty values before deploying:\n";
    f << "#   echo -n 'sk-your-key' | base64\n";
    f << "apiVersion: v1\n";
    f << "kind: Secret\n";
    f << "metadata:\n";
    f << "  name: " << name << "-secrets\n";
    f << "  namespace: " << config.namespace_ << "\n";
    f << "  labels:\n";
    f << "    app.kubernetes.io/name: " << name << "\n";
    f << "type: Opaque\n";
    f << "data:\n";
    f << "  OPENAI_API_KEY: \"\"\n";
    f << "  NEAM_API_KEY: \"\"\n";
  }

  // --- deployment.yaml ---
  {
    std::ofstream f("deploy/kubernetes/deployment.yaml");
    f << "# Generated by neamc deploy --target kubernetes\n";
    f << "apiVersion: apps/v1\n";
    f << "kind: Deployment\n";
    f << "metadata:\n";
    f << "  name: " << name << "\n";
    f << "  namespace: " << config.namespace_ << "\n";
    f << "  labels:\n";
    f << "    app.kubernetes.io/name: " << name << "\n";
    f << "spec:\n";
    f << "  replicas: " << config.replicas << "\n";
    f << "  revisionHistoryLimit: 5\n";
    f << "  selector:\n";
    f << "    matchLabels:\n";
    f << "      app.kubernetes.io/name: " << name << "\n";
    f << "  strategy:\n";
    f << "    type: RollingUpdate\n";
    f << "    rollingUpdate:\n";
    f << "      maxSurge: 1\n";
    f << "      maxUnavailable: 0\n";
    f << "  template:\n";
    f << "    metadata:\n";
    f << "      labels:\n";
    f << "        app.kubernetes.io/name: " << name << "\n";
    f << "    spec:\n";
    f << "      terminationGracePeriodSeconds: 30\n";
    f << "      containers:\n";
    f << "        - name: " << name << "\n";
    f << "          image: " << image << "\n";
    f << "          args: [\"--port\", \"" << config.port << "\", \"--workers\", \"4\"]\n";
    f << "          ports:\n";
    f << "            - name: http\n";
    f << "              containerPort: " << config.port << "\n";
    f << "              protocol: TCP\n";
    f << "          resources:\n";
    f << "            requests:\n";
    f << "              cpu: " << config.cpu_request << "\n";
    f << "              memory: " << config.memory_request << "\n";
    f << "            limits:\n";
    f << "              cpu: \"" << config.cpu_limit << "\"\n";
    f << "              memory: " << config.memory_limit << "\n";
    f << "          envFrom:\n";
    f << "            - configMapRef:\n";
    f << "                name: " << name << "-config\n";
    f << "            - secretRef:\n";
    f << "                name: " << name << "-secrets\n";
    f << "          startupProbe:\n";
    f << "            httpGet:\n";
    f << "              path: /health\n";
    f << "              port: http\n";
    f << "            initialDelaySeconds: 5\n";
    f << "            periodSeconds: 5\n";
    f << "            failureThreshold: 12\n";
    f << "          livenessProbe:\n";
    f << "            httpGet:\n";
    f << "              path: /health\n";
    f << "              port: http\n";
    f << "            periodSeconds: 15\n";
    f << "            timeoutSeconds: 5\n";
    f << "            failureThreshold: 3\n";
    f << "          readinessProbe:\n";
    f << "            httpGet:\n";
    f << "              path: /ready\n";
    f << "              port: http\n";
    f << "            periodSeconds: 5\n";
    f << "            timeoutSeconds: 3\n";
    f << "            failureThreshold: 3\n";
    f << "          securityContext:\n";
    f << "            runAsNonRoot: true\n";
    f << "            runAsUser: 1000\n";
    f << "            readOnlyRootFilesystem: true\n";
    f << "            allowPrivilegeEscalation: false\n";
    f << "          volumeMounts:\n";
    f << "            - name: tmp\n";
    f << "              mountPath: /tmp\n";
    f << "      volumes:\n";
    f << "        - name: tmp\n";
    f << "          emptyDir: {}\n";
  }

  // --- service.yaml ---
  {
    std::ofstream f("deploy/kubernetes/service.yaml");
    f << "# Generated by neamc deploy --target kubernetes\n";
    f << "apiVersion: v1\n";
    f << "kind: Service\n";
    f << "metadata:\n";
    f << "  name: " << name << "\n";
    f << "  namespace: " << config.namespace_ << "\n";
    f << "  labels:\n";
    f << "    app.kubernetes.io/name: " << name << "\n";
    f << "spec:\n";
    f << "  type: ClusterIP\n";
    f << "  selector:\n";
    f << "    app.kubernetes.io/name: " << name << "\n";
    f << "  ports:\n";
    f << "    - name: http\n";
    f << "      port: 80\n";
    f << "      targetPort: http\n";
    f << "      protocol: TCP\n";
  }

  // --- ingress.yaml ---
  {
    std::ofstream f("deploy/kubernetes/ingress.yaml");
    f << "# Generated by neamc deploy --target kubernetes\n";
    f << "apiVersion: networking.k8s.io/v1\n";
    f << "kind: Ingress\n";
    f << "metadata:\n";
    f << "  name: " << name << "\n";
    f << "  namespace: " << config.namespace_ << "\n";
    f << "  labels:\n";
    f << "    app.kubernetes.io/name: " << name << "\n";
    f << "  annotations:\n";

    if (config.ingress_class == "alb")
    {
      // AWS ALB Ingress Controller annotations
      f << "    kubernetes.io/ingress.class: alb\n";
      f << "    alb.ingress.kubernetes.io/scheme: internet-facing\n";
      f << "    alb.ingress.kubernetes.io/target-type: ip\n";
      f << "    alb.ingress.kubernetes.io/listen-ports: '[{\"HTTPS\":443}]'\n";
      f << "    alb.ingress.kubernetes.io/ssl-redirect: \"443\"\n";
      if (!config.certificate_arn.empty())
      {
        f << "    alb.ingress.kubernetes.io/certificate-arn: " << config.certificate_arn << "\n";
      }
      else
      {
        f << "    # alb.ingress.kubernetes.io/certificate-arn: <ACM_CERTIFICATE_ARN>\n";
      }
      f << "    alb.ingress.kubernetes.io/healthcheck-path: /health\n";
      f << "    alb.ingress.kubernetes.io/healthcheck-interval-seconds: \"15\"\n";
      f << "    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: \"5\"\n";
    }
    else
    {
      // Generic nginx ingress
      f << "    kubernetes.io/ingress.class: nginx\n";
    }

    f << "spec:\n";
    f << "  rules:\n";
    f << "    - http:\n";
    f << "        paths:\n";
    f << "          - path: /\n";
    f << "            pathType: Prefix\n";
    f << "            backend:\n";
    f << "              service:\n";
    f << "                name: " << name << "\n";
    f << "                port:\n";
    f << "                  name: http\n";
  }

  // --- hpa.yaml ---
  {
    std::ofstream f("deploy/kubernetes/hpa.yaml");
    f << "# Generated by neamc deploy --target kubernetes\n";
    f << "apiVersion: autoscaling/v2\n";
    f << "kind: HorizontalPodAutoscaler\n";
    f << "metadata:\n";
    f << "  name: " << name << "\n";
    f << "  namespace: " << config.namespace_ << "\n";
    f << "  labels:\n";
    f << "    app.kubernetes.io/name: " << name << "\n";
    f << "spec:\n";
    f << "  scaleTargetRef:\n";
    f << "    apiVersion: apps/v1\n";
    f << "    kind: Deployment\n";
    f << "    name: " << name << "\n";
    f << "  minReplicas: " << config.hpa_min << "\n";
    f << "  maxReplicas: " << config.hpa_max << "\n";
    f << "  metrics:\n";
    f << "    - type: Resource\n";
    f << "      resource:\n";
    f << "        name: cpu\n";
    f << "        target:\n";
    f << "          type: Utilization\n";
    f << "          averageUtilization: " << config.hpa_cpu_target << "\n";
    f << "  behavior:\n";
    f << "    scaleDown:\n";
    f << "      stabilizationWindowSeconds: 300\n";
    f << "      policies:\n";
    f << "        - type: Percent\n";
    f << "          value: 25\n";
    f << "          periodSeconds: 60\n";
    f << "    scaleUp:\n";
    f << "      stabilizationWindowSeconds: 30\n";
    f << "      policies:\n";
    f << "        - type: Percent\n";
    f << "          value: 100\n";
    f << "          periodSeconds: 60\n";
  }

  std::cout << "Generated Kubernetes manifests in deploy/kubernetes/\n";
  std::cout << "  namespace.yaml    - Namespace: " << config.namespace_ << "\n";
  std::cout << "  configmap.yaml    - Environment config\n";
  std::cout << "  secrets.yaml      - API keys (populate before deploying)\n";
  std::cout << "  deployment.yaml   - " << config.replicas << " replicas, rolling update\n";
  std::cout << "  service.yaml      - ClusterIP :80 -> :" << config.port << "\n";
  std::cout << "  ingress.yaml      - " << config.ingress_class << " ingress controller\n";
  std::cout << "  hpa.yaml          - Autoscale " << config.hpa_min << "-" << config.hpa_max
            << " pods\n";
}
}  // namespace neamc
