# CMake generated Testfile for 
# Source directory: /Users/praveengovindaraj/Neam_Home/repo/neam-nightly
# Build directory: /Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(vm_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/vm_test.exe")
set_tests_properties(vm_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;433;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(compiler_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/compiler_test.exe")
set_tests_properties(compiler_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;440;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(async_unit_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/async_unit_test.exe")
set_tests_properties(async_unit_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;446;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(runtime_executor_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/runtime_executor_test.exe")
set_tests_properties(runtime_executor_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;452;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(stdlib_list_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/stdlib_list_test.exe")
set_tests_properties(stdlib_list_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;458;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(stdlib_map_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/stdlib_map_test.exe")
set_tests_properties(stdlib_map_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;464;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(type_unification_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/type_unification_test.exe")
set_tests_properties(type_unification_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;486;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(test_framework_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/test_framework_test.exe")
set_tests_properties(test_framework_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;492;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(io_file_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/io_file_test.exe")
set_tests_properties(io_file_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;498;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(llm_adapter_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/llm_adapter_test.exe")
set_tests_properties(llm_adapter_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;513;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(http_client_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/http_client_test.exe")
set_tests_properties(http_client_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;519;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(package_manager_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/package_manager_test.exe")
set_tests_properties(package_manager_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;527;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(compile_run_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/compile_run_test.exe")
set_tests_properties(compile_run_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;533;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v068_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v068_test.exe")
set_tests_properties(v068_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;543;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v069_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v069_test.exe")
set_tests_properties(v069_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;553;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v070_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v070_test.exe")
set_tests_properties(v070_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;563;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v072_phase2_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v072_phase2_test.exe")
set_tests_properties(v072_phase2_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;573;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v072_manifest_agents_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v072_manifest_agents_test.exe")
set_tests_properties(v072_manifest_agents_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;579;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v090_data_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v090_data_agent_test.exe")
set_tests_properties(v090_data_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;589;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v091_etl_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v091_etl_agent_test.exe")
set_tests_properties(v091_etl_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;599;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v092_migration_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v092_migration_agent_test.exe")
set_tests_properties(v092_migration_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;609;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v093_dataops_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v093_dataops_agent_test.exe")
set_tests_properties(v093_dataops_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;619;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v094_governance_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v094_governance_agent_test.exe")
set_tests_properties(v094_governance_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;629;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v095_modeling_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v095_modeling_agent_test.exe")
set_tests_properties(v095_modeling_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;639;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v098_datascientist_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v098_datascientist_agent_test.exe")
set_tests_properties(v098_datascientist_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;649;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v0981_causal_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v0981_causal_agent_test.exe")
set_tests_properties(v0981_causal_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;655;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v0982_mlops_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v0982_mlops_agent_test.exe")
set_tests_properties(v0982_mlops_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;661;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v0983_databa_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v0983_databa_agent_test.exe")
set_tests_properties(v0983_databa_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;667;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v0984_datatest_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v0984_datatest_agent_test.exe")
set_tests_properties(v0984_datatest_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;673;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v099_dio_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v099_dio_agent_test.exe")
set_tests_properties(v099_dio_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;679;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v100_security_cloud_eval_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v100_security_cloud_eval_test.exe")
set_tests_properties(v100_security_cloud_eval_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;686;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v110_neamos_foundation_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v110_neamos_foundation_test.exe")
set_tests_properties(v110_neamos_foundation_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;693;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v120_prod_readiness_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v120_prod_readiness_test.exe")
set_tests_properties(v120_prod_readiness_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;700;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(v130_research_agent_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/v130_research_agent_test.exe")
set_tests_properties(v130_research_agent_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;707;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
add_test(neam_full_suite_test "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/build-windows-v12/neam_full_suite_test.exe")
set_tests_properties(neam_full_suite_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;717;add_test;/Users/praveengovindaraj/Neam_Home/repo/neam-nightly/CMakeLists.txt;0;")
subdirs("_deps/nlohmann_json-build")
subdirs("_deps/nlohmann_json_schema_validator-build")
subdirs("_deps/googletest-build")
subdirs("_deps/benchmark-build")
